pretrained:
  model_name: "bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12"
  cols: ["soc", "pt", "llt"]
  soc_epochs: 0
  pt_epochs : 0
  llt_epochs : 1
  epochs: 1
  batch_size: 512
  path: "bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12"
  complexity: 2